### PR TITLE
Remove unused member from eddsa algorithm base

### LINKED ISSUE #134: [bug] Wunused-private-field with Clang
**Describe the bug**
The following warning is shown during build:
```
/tmp/cirrus-ci-build/dep/jwt-cpp/include/jwt-cpp/jwt.h:1177:20: warning: private field 'md' is not used [-Wunused-private-field]
                        const EVP_MD* (*md)();
```

**Desktop:**
 - OS: FreeBSD 12.2
 - Compiler clang 10.0.1
 - Version 0.5.0 (b45bc9994d8087c5ba7aa1f1588302f04ae84c83)

### PR DESCRIPTION
**Pull request by prince-chrismc**
resolves #134

Minor API break but I doubt anyone is using the base class.

***

Additional Information ℹ️ 

- This matches the spec
  - https://tools.ietf.org/html/rfc8032#section-3.3
  - https://tools.ietf.org/html/rfc8032#section-4
- And OpenSSL docs
  -  https://www.openssl.org/docs/man1.1.1/man7/Ed25519.html
  - https://www.openssl.org/docs/man1.1.1/man7/Ed448.html

### CODE REVIEW

File: include/jwt-cpp/jwt.h [hunk 1]
```diff
@@ -1487,7 +1489,7 @@ namespace jwt {
 			 */
 			explicit ed448(const std::string& public_key, const std::string& private_key = "",
 						   const std::string& public_key_password = "", const std::string& private_key_password = "")
-				: eddsa(public_key, private_key, public_key_password, private_key_password, EVP_sha256, "EdDSA") {}
+				: eddsa(public_key, private_key, public_key_password, private_key_password, EVP_shake256, "EdDSA") {}
```
Comment (prince-chrismc) [inline include/jwt-cpp/jwt.h:1492]:
```suggestion
				: eddsa(public_key, private_key, public_key_password, private_key_password, "EdDSA") {}
```

**Review by Thalhammer — APPROVED** [review]
